#+TITLE: Ostrom

TODO https://mr.gy/blog/lisp-vendoring-quicklisp-nix.html

* Preliminaries.

Mostly developed over a remote connection. Using CCL 'cuz that's what Babel2
supports at the moment. Roswell provides a convenient way to get a
Quicklisp-enabled persistent REPL running. Anyway once Lisp is running with
Quicklisp I do something like:

#+BEGIN_SRC lisp
  (ql:quickload "swank")
  (swank:create-server :dont-close t)
#+END_SRC

SSH tunnel gets created like:

#+BEGIN_SRC sh
  ssh -L 4005:localhost:4005 me@my.site
#+END_SRC

Then `M-x slime-connect` and you're hacking!

* Package setup.

Qlot is awesome.

#+BEGIN_SRC lisp
  (ql:quickload "qlot")
#+END_SRC

#+BEGIN_SRC fundamental
  ql hunchentoot :latest
#+END_SRC

Pending figuring out a way to get Qlot working effectively across a remote
connection, Hunchentoot is in Quicklisp anyway!

#+BEGIN_SRC lisp
  (ql:quickload "hunchentoot")
#+END_SRC

CL-WHO for HTML gen (I've even tried to contribute to it!).

#+BEGIN_SRC lisp
  (ql:quickload "cl-who")
#+END_SRC

And Parenscript for JS gen.

#+BEGIN_SRC lisp
  (ql:quickload "parenscript")
#+END_SRC

* Creating a website.

Hunchentoot's easy handlers may be easy and dumb but the easy part is really
nice.

#+BEGIN_SRC lisp
  (hunchentoot:define-easy-handler (home :uri "/") ()
    (cl-who:with-html-output-to-string (*standard-output*)
      (:html
       (:head (:title "Ostrom"))
       (:body (:h1 "Ostrom")
              (:p "The quick brown fox jumps over the lazy dog.")
              (:p (format nil "~a" (nlp-tools:get-penelope-pos-tags "The quick brown fox jumps over the lazy dog.")))))))

  (hunchentoot:start (make-instance 'hunchentoot:easy-acceptor
                                    :port 8000
                                    :document-root "."))
#+END_SRC

Oh and to access the site from the outside you'll need to bind the Hunchentoot
port to the outside somehow. On my DigitalOcean droplet I do this with NGINX. I
also forward =/src/= to the Fossil server (which I start with =fossil server
--baseurl http://my.site/src=).

#+BEGIN_SRC conf
  server {
          listen 80 default_server;
          server_name my.site;
          location / {
                  proxy_pass http://127.0.0.1:8000;
          }
          location /src/ {
                  proxy_pass http://127.0.0.1:8080/;
          }
  }
#+END_SRC

* Babel2 setup.

  #+begin_src sh
    git clone https://github.com/EvolutionaryLinguisticsAssociation/Babel2
  #+end_src

  Disable the web interface since we have a custom one.

  #+begin_src lisp
    (defparameter *automatically-start-web-interface* nil)
  #+end_src

  Then we can actually load the system. TODO fix the hardcoding found
  here. TODO figure out how to keep the server from nuking my easy-handlers.

  #+begin_src lisp
    (load "../Babel2/init-babel")
    (ql:quickload "irl")
  #+end_src

  There is a =nlp-tools= package that lets us do things like this.

  #+begin_src lisp
    (ql:quickload "nlp-tools")
    (nlp-tools:get-penelope-tokens "I don't like homework")
  #+end_src

  Even better it has some parts of speech tagging built in.

  #+begin_src lisp
    (nlp-tools:get-penelope-pos-tags "The user must do thing 1 and thing 2")
  #+end_src

  Granted it's a web API but let's get a nice little API of our own setup.

** POS tagger endpoint.

   #+begin_src lisp
     (hunchentoot:define-easy-handler (pos-tagger :uri "/get-nouns") (utterance)
       (format t "~a" (nlp-tools:get-penelope-pos-tags utterance)))
   #+end_src
